# Generated by Django 4.2.6 on 2023-10-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planmeapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="datavisualization",
            old_name="type",
            new_name="types",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="user",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="dashboard", to="planmeapp.user"
            ),
        ),
        migrations.AddField(
            model_name="datavisualization",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_visualization",
                to="planmeapp.user",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="user",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="planmeapp.user"),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="planmeapp.user"
            ),
        ),
    ]
